contact_links:
  - name: GitHub Community Support
    url: https://github.com/fustilio/linguine/discussions
    about: Please leave your questions here or on Discord - Link below "Security Bug Bounty"
